version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: shortURL
    # tty: true
    ports:
      - 8080:8080
    env_file: .env
    depends_on: 
      - db
    volumes:
      - ./:/go/src/github.com/Tatsuemon/shortURL
  db:
    image: mysql:8.0
    container_name: shortURL-db
    ports:
      - 3306:3306
    env_file: .env
    volumes:
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - db-data:/var/lib/mysql
volumes:
  db-data: