version: "3"
services:
  app-test:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: anony-test
    ports:
      - 8080:8080
    env_file: .env.test
    depends_on: 
      - db-test
    volumes:
      - ./:/go/src/github.com/Tatsuemon/anony
  db-test:
    image: mysql:8.0
    container_name: anony-db-test
    ports:
      - 3306:3306
    env_file: .env.test
    volumes:
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - db-data-test:/var/lib/mysql
volumes:
  db-data-test: