// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: anony.proto

package rpc

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/emptypb"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *UserBase) Validate() error {
	return nil
}
func (this *CreateUserRequest) Validate() error {
	if this.User != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.User); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("User", err)
		}
	}
	return nil
}
func (this *CreateUserResponse) Validate() error {
	if this.User != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.User); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("User", err)
		}
	}
	return nil
}
func (this *LogInUserRequest) Validate() error {
	return nil
}
func (this *LogInUserResponse) Validate() error {
	if this.User != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.User); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("User", err)
		}
	}
	return nil
}
func (this *CreateAnonyURLRequest) Validate() error {
	return nil
}
func (this *CreateAnonyURLResponse) Validate() error {
	return nil
}
func (this *AnonyURL) Validate() error {
	return nil
}
func (this *ListAnonyURLsRequest) Validate() error {
	return nil
}
func (this *ListAnonyURLsResponse) Validate() error {
	for _, item := range this.AnonyUrls {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("AnonyUrls", err)
			}
		}
	}
	return nil
}
func (this *CountAnonyURLsResponse) Validate() error {
	return nil
}
