// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: short.proto

package rpc

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	_ "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *RegisterRequest) Validate() error {
	return nil
}
func (this *RegisterResponse) Validate() error {
	return nil
}
func (this *StartRequest) Validate() error {
	return nil
}
func (this *StartResponse) Validate() error {
	return nil
}
func (this *StopRequest) Validate() error {
	return nil
}
func (this *StopResponse) Validate() error {
	return nil
}
