name: Test
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: prepare db for test
      run: make prepare-test-db
    - name: go test
      run: make test
